name: Distlib 0.3.5 issue

on:
  push: {}

jobs:
  build:
    runs-on: windows-2022
    name: ${{ matrix.distlib }}-${{ matrix.type }}${{ matrix.bitness }}
    strategy:
      fail-fast: false
      matrix:
        distlib: ["0.3.3", "0.3.4", "0.3.5", "52de225"]
        type: ["t", "w"]
        bitness: [32, 64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Python embed archives
        shell: bash
        run: |
          if [[ ${{ matrix.bitness }} == 32 ]]; then
            curl -SLo python32.zip 'https://www.python.org/ftp/python/3.10.5/python-3.10.5-embed-win32.zip'
            unzip python32.zip -d python32
          else
            curl -SLo python64.zip 'https://www.python.org/ftp/python/3.10.5/python-3.10.5-embed-amd64.zip'
            unzip python64.zip -d python64
          fi
      - name: Build
        shell: bash
        run: ./build.sh "${{ matrix.distlib }}" launcher "${{ matrix.type }}" "${{ matrix.bitness }}"
      - name: Run
        shell: bash
        run: node ./run.js launcher-${{ matrix.type }}${{ matrix.bitness }}.exe
